#### 1-D Array

In [1]:
import numpy as np

In [2]:
list = [5,77,62,14]
array = np.array(list)

In [3]:
array

array([ 5, 77, 62, 14])

In [5]:
type(array)

numpy.ndarray

In [7]:
array.shape

(4,)

#### Multi-D Array

In [10]:
list1 = [7,5,8,9]
list2 = [7,2,9,3]
list3 = [8,5,4,1]
arr = np.array([list1,list2,list3])
arr

array([[7, 5, 8, 9],
       [7, 2, 9, 3],
       [8, 5, 4, 1]])

In [12]:
arr.shape

(3, 4)

In [13]:
arr.reshape(2,6)

array([[7, 5, 8, 9, 7, 2],
       [9, 3, 8, 5, 4, 1]])

#### Indexing of Array

In [14]:
arr.reshape(4,3)

array([[7, 5, 8],
       [9, 7, 2],
       [9, 3, 8],
       [5, 4, 1]])

In [15]:
list

[5, 77, 62, 14]

In [18]:
arr

array([[7, 5, 8, 9],
       [7, 2, 9, 3],
       [8, 5, 4, 1]])

In [22]:
arr[2,1]

5

In [35]:
arr[:2,2:5]

array([[8, 9],
       [9, 3]])

In [40]:
#arrange elements (start,stop,jump)

arr = np.arange(0,16,5)
arr

array([ 0,  5, 10, 15])

In [41]:
#replace value 

arr[1:]=16
arr

array([ 0, 16, 16, 16])

In [44]:
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])

In [47]:
np.random.rand(2,3)

array([[0.8136526 , 0.47077355, 0.66978267],
       [0.05152914, 0.71568219, 0.76912264]])